version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bookHour
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência dos dados do banco
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Monta o código-fonte local no container para desenvolvimento
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1  # Defina variáveis de ambiente adicionais, se necessário

volumes:
  postgres_data:
